import { Project, RentalProperty, TeamMember } from '@/types'

export const projects: Project[] = [
  {
    id: '1',
    slug: 'maple-heights-community',
    title: 'Maple Heights Community',
    tagline: 'Modern Living in the Heart of Mississauga',
    description: 'A vibrant master-planned community offering modern townhomes and single-family residences.',
    longDescription: 'Maple Heights Community is a thoughtfully designed master-planned neighborhood that brings together modern architecture, green spaces, and community living. Located in one of Mississauga\'s most desirable areas, this development offers a range of housing options from contemporary townhomes to executive single-family homes. Residents enjoy access to extensive parklands, walking trails, and a future community center.',
    address: '1450 Maple Ridge Drive',
    city: 'Mississauga',
    province: 'Ontario',
    postalCode: 'L5A 3K8',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80', 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80', 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80'],
    units: 245,
    status: 'Completed',
    completionDate: '2024',
    amenities: ['Community Center', 'Walking Trails', 'Playground', 'Tennis Courts', 'Swimming Pool'],
    schools: ['Maple Ridge Public School', 'St. Francis Xavier Secondary School', 'Sheridan College'],
    shopping: ['Square One Shopping Centre', 'Heartland Town Centre', 'Erin Mills Town Centre'],
    transit: ['Mississauga Transit', 'Go Transit', 'Highway 401', 'Pearson International Airport'],
    floorPlans: [
      { id: 'mh-2br', name: '2 Bedroom', bedrooms: 2, bathrooms: 2, sqft: 1050, price: 599000, image: '/images/floorplans/2br.jpg', svg: '' },
      { id: 'mh-3br', name: '3 Bedroom', bedrooms: 3, bathrooms: 2.5, sqft: 1450, price: 749000, image: '/images/floorplans/3br.jpg', svg: '' },
      { id: 'mh-4br', name: '4 Bedroom', bedrooms: 4, bathrooms: 3.5, sqft: 2100, price: 949000, image: '/images/floorplans/4br.jpg', svg: '' },
    ],
    features: ['Open Concept Layouts', 'Stainless Steel Appliances', 'Hardwood Flooring', 'Granite Countertops', 'Energy Efficient Windows', 'Smart Home Technology'],
    lat: 43.5890,
    lng: -79.6441,
    type: 'Residential',
  },
  {
    id: '2',
    slug: 'northern-pines-estates',
    title: 'Northern Pines Estates',
    tagline: 'Luxury Living in the Foothills of Calgary',
    description: 'Executive estate homes nestled against the stunning backdrop of the Rocky Mountains.',
    longDescription: 'Northern Pines Estates represents the pinnacle of luxury living in Calgary. Set against the majestic Rocky Mountains, this exclusive community features custom-built executive homes on large lots, with breathtaking views and premium finishes throughout.',
    address: '785 Evergreen Trail',
    city: 'Calgary',
    province: 'Alberta',
    postalCode: 'T2Y 4H8',
    image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1200&q=80', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80', 'https://images.unsplash.com/photo-1600566753086-00f18f6bae40?w=1200&q=80'],
    units: 120,
    status: 'Completed',
    completionDate: '2023',
    amenities: ['Private Clubhouse', 'Fitness Center', 'Nature Trails', 'Ski Storage', 'Winter Garden'],
    schools: ['Evergreen Elementary School', 'Calgary Academy', 'University of Calgary'],
    shopping: ['Chinook Centre', 'Southcentre Mall', 'Deerfoot Meadows'],
    transit: ['Calgary Transit', 'C-Train', 'Stoney Trail', 'Highway 22X'],
    floorPlans: [
      { id: 'np-2br', name: '2 Bedroom + Den', bedrooms: 2, bathrooms: 2, sqft: 1200, price: 699000, image: '/images/floorplans/2br.jpg', svg: '' },
      { id: 'np-3br', name: '3 Bedroom', bedrooms: 3, bathrooms: 2.5, sqft: 1700, price: 899000, image: '/images/floorplans/3br.jpg', svg: '' },
      { id: 'np-4br', name: '4 Bedroom Executive', bedrooms: 4, bathrooms: 3.5, sqft: 2600, price: 1299000, image: '/images/floorplans/4br.jpg', svg: '' },
    ],
    features: ['Mountain Views', 'Heated Floors', 'Chef\'s Kitchen', 'Wine Cellar', 'Home Automation', 'EV Charging'],
    lat: 50.9423,
    lng: -114.1033,
    type: 'Residential',
  },
  {
    id: '3',
    slug: 'riverstone-residences',
    title: 'Riverstone Residences',
    tagline: 'Where Urban Living Meets Natural Beauty',
    description: 'Elegant condominiums along the scenic Ottawa River with panoramic views.',
    longDescription: 'Riverstone Residences offers a unique blend of urban sophistication and natural tranquility along the Ottawa River. These premium condominiums feature floor-to-ceiling windows that frame stunning river views, world-class amenities, and a location steps from Ottawa\'s best dining, shopping, and cultural attractions.',
    address: '222 Riverfront Boulevard',
    city: 'Ottawa',
    province: 'Ontario',
    postalCode: 'K1P 1A1',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80', 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80'],
    units: 180,
    status: 'Under Construction',
    completionDate: '2025',
    amenities: ['Concierge Service', 'Rooftop Terrace', 'Indoor Pool', 'Spa & Sauna', 'Yoga Studio', 'Pet Spa'],
    schools: ['University of Ottawa', 'Carleton University', 'Lisgar Collegiate Institute'],
    shopping: ['Rideau Centre', 'ByWard Market', 'Sparks Street'],
    transit: ['OC Transpo', 'LRT Confederation Line', 'Highway 417', 'Ottawa International Airport'],
    floorPlans: [
      { id: 'rs-2br', name: '2 Bedroom', bedrooms: 2, bathrooms: 2, sqft: 950, price: 549000, image: '/images/floorplans/2br.jpg', svg: '' },
      { id: 'rs-3br', name: '3 Bedroom Penthouse', bedrooms: 3, bathrooms: 2, sqft: 1400, price: 799000, image: '/images/floorplans/3br.jpg', svg: '' },
    ],
    features: ['River Views', 'Italian Cabinetry', 'Quartz Countertops', 'Engineered Hardwood', 'Smart Thermostat', 'Gym Access'],
    lat: 45.4215,
    lng: -75.6993,
    type: 'Condominium',
  },
  {
    id: '4',
    slug: 'cedar-grove-townhomes',
    title: 'Cedar Grove Townhomes',
    tagline: 'Family-Friendly Living in London, Ontario',
    description: 'Beautiful townhomes in a quiet, family-oriented neighborhood.',
    longDescription: 'Cedar Grove Townhomes offers the perfect setting for growing families. These beautifully designed townhomes feature modern open-concept layouts, private backyards, and a sense of community that makes Cedar Grove one of London\'s most sought-after neighborhoods.',
    address: '114 Cedar Park Lane',
    city: 'London',
    province: 'Ontario',
    postalCode: 'N6G 4S2',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80', 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80', 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&q=80'],
    units: 85,
    status: 'Completed',
    completionDate: '2024',
    amenities: ['Community Park', 'Splash Pad', 'Dog Park', 'BBQ Areas', 'Community Garden'],
    schools: ['Cedar Park Public School', 'A.B. Lucas Secondary School', 'Western University'],
    shopping: ['Masonville Place', 'White Oaks Mall', 'Cherryhill Village Mall'],
    transit: ['London Transit', 'VIA Rail', 'Highway 401', 'London International Airport'],
    floorPlans: [
      { id: 'cg-2br', name: '2 Bedroom', bedrooms: 2, bathrooms: 1.5, sqft: 950, price: 449000, image: '/images/floorplans/2br.jpg', svg: '' },
      { id: 'cg-3br', name: '3 Bedroom', bedrooms: 3, bathrooms: 2.5, sqft: 1350, price: 549000, image: '/images/floorplans/3br.jpg', svg: '' },
      { id: 'cg-4br', name: '4 Bedroom', bedrooms: 4, bathrooms: 3, sqft: 1800, price: 679000, image: '/images/floorplans/4br.jpg', svg: '' },
    ],
    features: ['Private Entrance', 'Finished Basement', 'Fenced Yard', 'Single Garage', 'Energy Star Rated', 'Landscaping Included'],
    lat: 43.0108,
    lng: -81.2720,
    type: 'Townhome',
  },
  {
    id: '5',
    slug: 'lakeview-luxury-condominiums',
    title: 'Lakeview Luxury Condominiums',
    tagline: 'Waterfront Living on Lake Ontario',
    description: 'Premium lakeside condos with breathtaking views of Lake Ontario.',
    longDescription: 'Lakeview Luxury Condominiums redefine waterfront living in Burlington. Each residence is designed to maximize the stunning views of Lake Ontario, with expansive balconies, floor-to-ceiling windows, and premium finishes throughout.',
    address: '95 Lakeshore Avenue',
    city: 'Burlington',
    province: 'Ontario',
    postalCode: 'L7R 4B2',
    image: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&q=80', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80', 'https://images.unsplash.com/photo-1600566753086-00f18f6bae40?w=1200&q=80'],
    units: 210,
    status: 'Pre-Construction',
    completionDate: '2026',
    amenities: ['Infinity Pool', 'Rooftop Terrace', 'Fitness Center', 'Wine Lounge', 'Guest Suites', 'Car Wash Bay'],
    schools: ['Burlington Central High School', 'Nelson High School', 'McMaster University'],
    shopping: ['Mapleview Centre', 'Burlington Mall', 'Downtown Burlington'],
    transit: ['Burlington Transit', 'Go Transit', 'QEW', 'Highway 403'],
    floorPlans: [
      { id: 'lv-1br', name: '1 Bedroom + Den', bedrooms: 1, bathrooms: 1, sqft: 650, price: 499000, image: '/images/floorplans/2br.jpg', svg: '' },
      { id: 'lv-2br', name: '2 Bedroom', bedrooms: 2, bathrooms: 2, sqft: 1100, price: 699000, image: '/images/floorplans/2br.jpg', svg: '' },
      { id: 'lv-3br', name: '3 Bedroom Penthouse', bedrooms: 3, bathrooms: 2, sqft: 1800, price: 1199000, image: '/images/floorplans/3br.jpg', svg: '' },
    ],
    features: ['Lake Views', 'Subzero Appliances', 'Marble Bathrooms', 'Walk-in Closets', 'Wine Fridge', 'Motorized Blinds'],
    lat: 43.3255,
    lng: -79.7990,
    type: 'Condominium',
  },
  {
    id: '6',
    slug: 'aurora-hills-community',
    title: 'Aurora Hills Community',
    tagline: 'A New Standard of Living in Edmonton',
    description: 'An innovative community designed for modern families in Edmonton.',
    longDescription: 'Aurora Hills Community represents the future of suburban living in Edmonton. This master-planned community combines innovative architecture with sustainable design principles, featuring a mix of single-family homes, townhomes, and condominiums.',
    address: '401 Aurora Crescent',
    city: 'Edmonton',
    province: 'Alberta',
    postalCode: 'T5T 6M5',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80', 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80'],
    units: 320,
    status: 'Under Construction',
    completionDate: '2025',
    amenities: ['Community Hub', 'Indoor Recreation Centre', 'Skate Park', 'Community Garden', 'Green Spaces', 'Sports Fields'],
    schools: ['Aurora Elementary School', 'Jasper Place High School', 'University of Alberta'],
    shopping: ['West Edmonton Mall', 'Southgate Centre', 'Kingsway Mall'],
    transit: ['Edmonton Transit Service', 'Valley Line LRT', 'Anthony Henday Drive', 'Edmonton International Airport'],
    floorPlans: [
      { id: 'ah-2br', name: '2 Bedroom Townhome', bedrooms: 2, bathrooms: 1.5, sqft: 900, price: 399000, image: '/images/floorplans/2br.jpg', svg: '' },
      { id: 'ah-3br', name: '3 Bedroom', bedrooms: 3, bathrooms: 2.5, sqft: 1400, price: 529000, image: '/images/floorplans/3br.jpg', svg: '' },
      { id: 'ah-4br', name: '4 Bedroom Executive', bedrooms: 4, bathrooms: 3, sqft: 2000, price: 689000, image: '/images/floorplans/4br.jpg', svg: '' },
    ],
    features: ['Solar Ready', 'HRV System', 'Triple Pane Windows', 'LED Lighting', 'Low Flow Fixtures', 'Smart Thermostat'],
    lat: 53.5362,
    lng: -113.6274,
    type: 'Mixed-Use',
  },
]

export const rentals: RentalProperty[] = [
  { id: 'r1', title: 'Modern 2BR Apartment - Maple Heights', description: 'Beautiful 2-bedroom apartment in the heart of Maple Heights Community.', images: ['/images/rentals/rental-1.jpg'], price: 2200, bedrooms: 2, bathrooms: 1, parking: 1, sqft: 850, availabilityDate: '2025-07-01', address: '1450 Maple Ridge Dr', city: 'Mississauga', province: 'ON', amenities: ['In-suite Laundry', 'Central AC', 'Balcony', 'Gym Access'], projectId: '1', projectName: 'Maple Heights Community', lat: 43.5890, lng: -79.6441 },
  { id: 'r2', title: 'Executive 3BR Townhome - Riverstone', description: 'Spacious 3-bedroom townhome near the Ottawa River.', images: ['/images/rentals/rental-2.jpg'], price: 3200, bedrooms: 3, bathrooms: 2.5, parking: 2, sqft: 1400, availabilityDate: '2025-08-01', address: '222 Riverfront Blvd', city: 'Ottawa', province: 'ON', amenities: ['Private Entrance', 'Finished Basement', 'Garage', 'Backyard'], projectId: '3', projectName: 'Riverstone Residences', lat: 45.4215, lng: -75.6993 },
  { id: 'r3', title: 'Luxury 1BR Condo - Lakeview', description: 'Stunning 1-bedroom condo with Lake Ontario views.', images: ['/images/rentals/rental-3.jpg'], price: 2600, bedrooms: 1, bathrooms: 1, parking: 1, sqft: 650, availabilityDate: '2025-06-15', address: '95 Lakeshore Ave', city: 'Burlington', province: 'ON', amenities: ['Pool Access', 'Gym', 'Concierge', 'Balcony'], projectId: '5', projectName: 'Lakeview Luxury Condominiums', lat: 43.3255, lng: -79.7990 },
  { id: 'r4', title: 'Family 4BR Home - Cedar Grove', description: 'Perfect family home in quiet London neighborhood.', images: ['/images/rentals/rental-4.jpg'], price: 2800, bedrooms: 4, bathrooms: 3, parking: 2, sqft: 1800, availabilityDate: '2025-09-01', address: '114 Cedar Park Ln', city: 'London', province: 'ON', amenities: ['Fenced Yard', 'Finished Basement', 'Double Garage', 'Deck'], projectId: '4', projectName: 'Cedar Grove Townhomes', lat: 43.0108, lng: -81.2720 },
  { id: 'r5', title: '3BR Mountain View Home - Northern Pines', description: 'Executive home with stunning mountain views.', images: ['/images/rentals/rental-5.jpg'], price: 3500, bedrooms: 3, bathrooms: 2.5, parking: 2, sqft: 1700, availabilityDate: '2025-07-15', address: '785 Evergreen Trail', city: 'Calgary', province: 'AB', amenities: ['Mountain View', 'Heated Garage', 'Home Office', 'Wine Cellar'], projectId: '2', projectName: 'Northern Pines Estates', lat: 50.9423, lng: -114.1033 },
  { id: 'r6', title: '2BR Townhome - Aurora Hills', description: 'Modern townhome in Edmonton\'s newest community.', images: ['/images/rentals/rental-6.jpg'], price: 1800, bedrooms: 2, bathrooms: 1.5, parking: 1, sqft: 900, availabilityDate: '2025-08-15', address: '401 Aurora Cres', city: 'Edmonton', province: 'AB', amenities: ['Community Pool', 'Park Access', 'Balcony', 'In-suite Laundry'], projectId: '6', projectName: 'Aurora Hills Community', lat: 53.5362, lng: -113.6274 },
]

export const teamMembers: TeamMember[] = [
  { id: 't1', name: 'James Mitchell', role: 'CEO & Founder', department: 'Executive', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', description: 'Over 25 years of experience in Canadian real estate development.' },
  { id: 't2', name: 'Sarah Chen', role: 'Chief Architect', department: 'Architecture', image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80', description: 'Award-winning architect specializing in sustainable community design.' },
  { id: 't3', name: 'Michael O\'Brien', role: 'VP of Construction', department: 'Construction', image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80', description: 'Leading large-scale residential and commercial projects across Canada.' },
  { id: 't4', name: 'Emily Watson', role: 'Director of Urban Planning', department: 'Urban Planning', image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80', description: 'Creating vibrant, walkable communities with smart growth principles.' },
  { id: 't5', name: 'David Park', role: 'Senior Structural Engineer', department: 'Engineering', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80', description: 'Expert in innovative structural solutions for complex developments.' },
  { id: 't6', name: 'Lisa Tremblay', role: 'Head of Property Management', department: 'Management', image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80', description: 'Ensuring exceptional living experiences for all Maple Crest residents.' },
]

export const companyStats = {
  yearsExperience: 15,
  homesBuilt: 500,
  communitiesDeveloped: 50,
  happyResidents: 1000,
  projectsInProgress: 6,
  teamMembers: 250,
}

export const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/projects', label: 'Projects' },
  { href: '/buy', label: 'Buy' },
  { href: '/rent', label: 'Rent' },
  { href: '/viewing', label: 'Book Viewing' },
  { href: '/about', label: 'About' },
  { href: '/contact', label: 'Contact' },
]
